### ISSUE TITLE
Kotlin x.times(y) not working

### ISSUE THREAD

**Issue by Simolation** [tobiasschuerg/android-money#1]
When I try to multiply money it is not possibe and shows an error:

`Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
@InlineOnly public inline operator fun BigDecimal.times(other: BigDecimal): BigDecimal defined in kotlin
@InlineOnly public inline operator fun BigInteger.times(other: BigInteger): BigInteger defined in kotlin`

Neither x * y nor x.times(y) is working.

When I decompile the Money.class I can see, that the times function is missing. div, minus... are all there, but times is missing.

**Comment by Simolation** [comment]
You would just have to add

` operator fun times(number: BigDecimal): Money {
        val result = amount.times(number)
        return Money(result, currency)
    }`

to Money.kt and it works as it is supposed to

**Comment by tobiasschuerg** [comment]
Thanks for reporting. 

Please try version `0.5`: 

[implementation 'com.github.tobiasschuerg:android-money:v0.5'](https://jitpack.io/#tobiasschuerg/android-money/v0.5)
