### ISSUE TITLE
Is BigDecimal supported as input type?

### ISSUE THREAD

**Issue by longquangpham90** [tobiasschuerg/android-money#3]
Hi team dev!
We user library, but we want use BigDecimal Format number, library can not support

**Comment by tobiasschuerg** [comment]
@longquangpham90 I don't really understand the issue, can you please explain?

**Comment by longquangpham90** [comment]
@tobiasschuerg so we want input type class BigDecimal
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html

**Comment by tobiasschuerg** [comment]
You can create Money objects from BigDecimals already:
```
val pi = BigDecimal(3.14159265359)
Money(pi, usDollar)
```

Also for all operations BigDecimal is used internally
https://github.com/tobiasschuerg/android-money/blob/f2965c4013cab966b30995c3c584b4a43a0f0359/money/src/main/java/de/tobiasschuerg/money/Money.kt#L19-L27

Does this address your issue?
